name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Run tests with Maven Wrapper
        run: ./mvnw -B -DskipTests=false test
        env:
          MAVEN_OPTS: -Xmx2g
